### ISSUE TITLE
Nesting?

### ISSUE THREAD

**Issue by arjan** [speechmarkdown/docs-speechmarkdown-reference#3]
"Regular" markdown can be arbitrarily nested. It seems that currently this is not in the design of speech markdown. Is this by choice? SSML lends very well to nesting.

```
(a [2s] break in a slow sentence)[rate:"slow"]
```

It might make more sense to use sections for this. In that case, it might make sense to add more prosody options to the section specs, e.g. pitch, rate, volume, emphasis, and whisper.

**Comment by rmtuckerphx** [comment]
Instead of nesting, I would move forward with extending the tags that can be in a section.

**Comment by arjan** [comment]
Yep makes sense
